language: java
install: true
script:
  - mvn install

dist: focal

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="774796de-912c-4ffc-9282-92fff75f7246"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - vldmrqst@gmail.com
    on_success: never
    on_failure: always